src/server/fs/lib/fs-manager.js
[DESC.] Binary check algorithm is incorrect when file size is less than 800 bytes. So, check the file size.
=> [BUGFIX] (ODP-331) Fix the searchFiles() api bug

src/server/fs/lib/fs-manager.js
When the stdio buffer of child process was full and parent process does not clear it, child process hang until the buffer is empty.
So, changed to use the parent's stdio.
Signed-off-by: Sangjin Kim <sangjin3.kim@samsung.com>
=> Fix the extractZip() api bug.

src/server/conf/default-conf.js, src/server/fs/lib/container/lxcd.js
- implement lxc container life cycle management
-- no internal ip management mechanism
-- below sudo permissions are needed:
--- lxc-start, lxc-stop
--- lxc-attach, lxc-wait
Change-Id: I2b2064d1853e7c02115c73698563689a29654c0b
Signed-off-by: HyunSeok Kil <hyunseok.kil@samsung.com>
=> fs: supply one container per fsid on lxc

src/server/fs/lib/fs-manager.js
[DESC.]
- deny to access parent directory of the fsid root
- implemented by WebidaFs class instead Resource
- fix invalid resource instance for authorization check
related with ODP-518
=> [BUGFIX] (#98) make up for vulnerabilities during creating directory

src/server/fs/lib/fs-manager.js, src/server/package.json
- [FEATURE] add `replaceFiles` API to the file server
- [BUGFIX] revert `package.json` file
- "http-proxy" package is still used in `app-manager` for serving nodejs app
=> Add `replaceFiles` API and revert package.json file

src/server/fs/lib/fs-manager.js
[DESC.]
- It is caused by the way of processing with request params on fs server.
- Issues
- webida/webida-client#492
- webida/webida-client#490
=> [BUGFIX] fix 'session id of a notification is unknown' error.

src/server/common/auth-manager.js, src/server/conf/default-conf.js
[DESC.]
- return to use http connection instead of SSL between one of servers using `authManager` and auth server
- configuration key name changed ( `hostInfo` -> `internalAccessInfo` )
- follow coding conventions
=> [TASK] Use http connection between servers

src/server/auth/lib/user-manager.js
[DESC.]
- There was an weird limitless holding status when Github API `/user/emails` request was sent using `https.request()`.
- So, using `request` package to request Github API now.
=> [BUGFIX] (#115) fix "Login with Github" problems

src/server/auth/lib/user-manager.js
- This is for prevent cross-origin (302 redirected from app server to auth server) issue.
- Once Guest login(requested from app server) is successfully ended, returnTo variable on the user session should be cleaned.
[REF log]
XMLHttpRequest cannot load https://auth.webida.net/webida/api/oauth/guestlogin. The request was redirected to 'https://auth.webida.net/webida/api/oauth/authorize?response_type=token&redi…&client_id=E9CXCte9dnUU1GID&skip_decision=false&type=web_server&state=site', which is disallowed for cross-origin requests that require preflight.
=> [BUGFIX] (#117) fix 'Server Unreachable' error on Guest login

src/server/package.json
[DESC.]
- winston v2.0 have a problem with webida-server
[REF log]
/home/webida/webida-server/webida.net/server/common/log-manager.js:65
new (winston.transports.DailyRotateFile)({
^
TypeError: undefined is not a function
at Object.<anonymous> (/home/webida/webida-server/webida.net/server/common/log-manager.js:65:13)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at svcType (/home/webida/webida-server/webida.net/server/unit-manager.js:78:14)
at parseCommandLine (/home/webida/webida-server/webida.net/server/unit-manager.js:66:12)
at Object.<anonymous> …
=> [BUGFIX] winston version fixing

src/server/app/app.js, src/server/conf/default-conf.js
[DESC.]
- If the server is launched without `useReverseProxy` setting, the domain of the cookie shouldn't be started with '.'.
=> [BUGFIX] fix bug related with setting cookie

src/server/fs/lib/console-manager.js, src/server/package.json
[DESC.]
- IDE terminal module is changed from terminal.js to term.js. So adjust the protocol to the new client.
- Remove the `socket.io-stream` dependency from `package.json`
Thanks to WSDK team.
Related with the commit#b57958795c3104f987edb78d2a5db5044cbb45b1
[ISSUES]
webida/webida-client#459
webida/webida-client#533
webida/webida-client#534
=> [IMPROVEMENT] Change the terminal protocol

src/server/conf/default-conf.js, src/server/fs/lib/linuxfs/btrfs.js, src/system-configs/sudoers
- moved lxc path to /home/webida/lxc to /var/lib/lxc
- fixed btrfs to refer right configuration properties
- fixed sudoer sample to see right btrfs util in /sbin (ubuntu default)
=> More works for VM

src/system-configs/upstart-configs/units/webida-batch.conf
=> [TASK] add batch server upstart script

src/server/fs/lib/Resource.js, src/server/fs/lib/console-manager.js, src/server/fs/lib/fs-manager.js, src/server/fs/lib/fs-service.js, src/server/fs/lib/webidafs.js
[DESC.]
- add `maxDepth` option to list API
- refactoring `fs-manager.js`
- separated into `fs-service.js`(access file system) and `Resource.js`(model)
- remove needless functions
- clean up some duplicated methods
=> [TASK] add maxDepth option to list API

src/server/common/auth-manager.js, src/server/common/http-logger.js, src/server/fs/lib/fs-manager.js, src/server/notify/lib/ntf.js
wtill working on #133 
- lowered upload/download log of fs-manager to debug
(data will be logged in access log, too)
- fixed http-logger's logging message to respect whole HTTP message
- lowered 'channel not found error' log level to debug, until it's not permanent.
- lowered some auth-client info log to debug
=> cleaning more logs 

src/server/common/logger-factory.js
- will not crash anymore - syslog process name will be set to argv[1]
if global.app is missing
=> fixed logging of *-install/uninstall scripts

src/server/fs/bin/git.sh, src/server/fs/lib/container/lxc.js, src/system-configs/sudoers
- With `su` command, $HOME env variable reset.
- Let `git.sh` be executed without `sudo su` command. (It'd had problem until I added `export HOME=$HOME;` in this `git.sh` file.
=> [BUGFIX] Using no 'su' command with 'git.sh'

src/server/fs/lib/console-manager.js, src/server/fs/lib/container/Container.js
[DESC.]
- change listening event(checking process finished) from `'exit'` to ``'close'` because the `'close'` event wait until stream closes
=> [BUGFIX] No stdout with `git config --get-regexp user` command.

src/server/common/http-logger.js, src/server/fs/lib/flinkmap.js
resolves #152 
- Orphan links in DB will not print error but warning message
- removed 'stale' property in access logs
- added try-catch and server logs for access log data
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/195)
=> fixing some misc error logs

src/server/auth/lib/user-manager.js
- third party (google or github) oauth login then client page must redirect first page
if (!req.session.retrunTo) req.session.returnTo = req.session.opener;  is not working.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/196)
=> [TASK] fix a address of login time browser redirect

src/server/app/lib/app-manager.js, src/server/conf/default-conf.js, src/server/package.json
- changed dashboard app domain to 'dashboard', not empty
- added default app routing logic for dashboard
- bumped server version to 1.7
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/202)
=> [TASK] added default app routing

src/server/auth/lib/user-manager.js, src/server/auth/lib/userdb.js, src/server/conf/checker.js, src/server/conf/default-conf.js
- separated smtp configuration from sign-up config
- fixed smtp configuration to node-mailer options form
- fixed sender address to `no-reply@{config.domain}`
- fixed checker.js to check smtp host config (default is empty);
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/204)
=> [BUGFIX] applying config to node-mailer transport
