- src/server/app/app.js
- src/server/app/lib/app-manager.js
- src/server/auth/lib/oauth2-manager.js
- src/server/conf/default-conf.js
- Configurations fixed & updated
- Default configurations and some paths in script files was modified.
- New Deploy Options added
- Made deploy options of server to be delivered by cookie.
- OAuth redirect URL issue was solved.
> [FIX] [TASK] Server configurations had been updated and OAuth redirectURL issue had been solved.

- README.md
- doc/quick-guide.md
- src/server/conf/default-conf.js
* Added quick guide
* No reverse proxy as default configuration. Extract some hardcoded strings in the configuration file.
> Guide document updated and configuration file modified.

- src/server/auth/lib/userdb.js
- [TASK] follow the code conventions
- [BUGFIX] (WTC-3205) allow the pending users to request re-signup
> Fix bug and refine code

- src/server/app-uninstall.js
- src/server/app/uninstall.js
- src/server/auth-uninstall.js
- src/server/auth/uninstall.js
- src/server/build/test/test-build.js
- src/server/fs/uninstall.js
and make them to use configuration file.
and refine some code according to the code convention
> [TASK] (ODP-171) remove hard-coded connection information 

- src/server/app/app.js
- src/server/app/lib/app-manager.js
- src/server/app/views/error.ejs
- src/server/auth/lib/oauth2-manager.js
- src/server/auth/views/error.ejs
- src/server/common/utils.js
[DESC] It was applied for the following messages.
- 404: ClientError: Requested subpath is directory, and it is failed to read directory entry
- 404: ClientError: File not found
- 404: Cannot find app for url. Check app domain or url.
- 404: This app is not running.
- 401: Redirect url mismatch
- 401: Unknown client ID
> [TASK] (ODP-323) write error page of the app/auth server

- src/server/fs/lib/fs-manager.js
> show detail error message when user exceed quota limit 

- src/server/fs/lib/console-manager.js
[FEATURE] (ODP-414) expand ip range for lxc-execute from "10.0.3.2~10.0.3.254/24" to "10.0.0.2~10.255.255.254/8"
> [FEATURE] (ODP-414) expand ip range

- src/server/tests/default-config.js
- src/server/tests/tc-impl/app_test.js
- src/server/tests/tc-impl/auth_test.js
- src/server/tests/tc-impl/fs_test.js
- src/server/tests/tc-impl/fssvc_test.js
- src/server/tests/testRunner.html
Signed-off-by: Sangjin Kim <sangjin3.kim@samsung.com>
> Add the unit test for fs server api.

- doc/advanced-guide.md
- doc/lxc-guide.md
[DESC.] 
Fix the out-dated contents
> [DOCUMENTATION] Fix content errors of guides

- src/server/app/lib/app-manager.js
Signed-off-by: HyunSeok Kil <hyunseok.kil@samsung.com>
> Fix the invalid domain variable

- src/server/fs/fs.js
- src/server/fs/lib/console-manager.js
- src/server/fs/lib/fs-manager.js
- src/server/package.json
> [FEATURE] Implement terminal service

- src/server/fs/lib/webidafs.js
- create WebidaFS instance with database entry
Change-Id: I59c51762d8b184bb662352d4c3adbb3f67df9901
> [BUGFIX] missing file to support terminal

- src/server/tests/tc-impl/fs_test.js
- FS is created for fs api test, delete it after test finished.
- Fix some jshint error.
>  Fix fs api test bug.

- src/server/tests/tc-impl/app_test.js
- src/server/tests/tc-impl/auth_test.js
- src/server/tests/tc-impl/fs_test.js
- src/server/tests/tc-impl/fssvc_test.js
- src/server/tests/testRunner.html
- Create custom logger to print object.
- Refine log messages to debug more easily.
- Disable app deploy api related tests.
- Disable fs archive api related tests.
Change-Id: If4afface61ee6b820993f5619a4f07b0301b81c8
Signed-off-by: Sangjin Kim <sangjin3.kim@samsung.com>
> [TASK] Refine log messages.

- src/server/auth/views/login.ejs
[DESC.]
width=520px, user-scalable=no
> [IMPROVEMENT] (ODP-1) add viewport options to login page for mobile accessibility

- src/server/auth/lib/oauth2-manager.js
- src/server/common/auth-manager.js
related with webida/webida-client#206
> [BUGFIX] fix bug occurred while verifying and registering token

- src/server/auth/lib/userdb.js
> [BUGFIX] fix parsing error occurred while getting user's authorized resources

- src/server/app/lib/app-manager.js
- src/server/auth/lib/userdb.js
- src/server/conf/mapper/group-mapper.json5
- src/server/conf/mapper/policy-mapper.json5
> [BUGFIX] resolve query issues related with deleting account.

- src/server/common/auth-manager.js
- src/server/fs/lib/fs-manager.js
- src/server/fs/lib/linuxfs/xfs.js
When error occured during fs creation
- rollback fs, policy
- rollback xfs quota
Change-Id: I7000bec1b68a1f8c204e83e9fb5642db155e17ee
Signed-off-by: HyunSeok Kil <hyunseok.kil@samsung.com>
> fs: implement transaction of fs creation

- src/server/fs/lib/fs-manager.js
* give a guarantee of unlinking uploaded files
* fix the url-encoded name of downloaded file
> fix some bug for downloading and uploading

- README.md
- doc/advanced-guide.md
- doc/prerequisites.md
- doc/quick-guide.md
[DESC.]
- update installation/uninstallation guide
- update database installation guide
> [DOCUMENTATION] update document details

- src/server/conf/default-conf.js
- src/server/fs/lib/console-manager.js
- src/server/fs/lib/container.js
- src/server/fs/lib/container/docker.js
- src/server/fs/lib/container/exec.js
- src/server/fs/lib/container/lxc.js
- src/server/fs/lib/container/none.js
- src/server/fs/lib/linuxfs/btrfs.js
- src/server/fs/lib/linuxfs/default.js
- src/server/fs/lib/linuxfs/xfs.js
- src/server/fs/lib/linuxfs/xfs_util.sh
- src/server/fs/lib/webidafs.js
implement container framework to extend another container type such as docker
Change-Id: I0a7e1901ee3cf83eae05546b040d91e43b967331
Signed-off-by: HyunSeok Kil <hyunseok.kil@samsung.com>
> fs: implement container framework

- doc/schema.sql
- src/server/auth/lib/userdb.js
- MySQL DB initial script
- [BUGFIX] prevent unexpected 500 error using expired token
- Apply coding convention on `userdb.js`
> [TASK] Add DB Schema and fix bug

- src/server/auth/auth.js
- src/server/auth/lib/user-manager.js
- src/server/auth/lib/userdb.js
- src/server/conf/default-conf.js
- new API added for guest-login (not applied in webida-*.js yet)
- new configuration added to enable/disable guest-mode features
> [FEATURE] (#82) added guest-login API

- src/server/app/lib/app-manager.js
- src/server/batch/batch.js
- src/server/batch/guestReaper.js
- src/server/conf/default-conf.js
- src/server/conf/mapper/token-mapper.json5
- src/server/conf/mapper/user-mapper.json5
- src/server/fs/lib/fs-manager.js
- src/server/package.json
- src/server/unit-manager.js
- added new unit, batch, based on node-cron
- added some configurations in default-conf.js for batch unit
- added a batch job for reaping expired guest accounts
- modified unit manager not to fork child process of batch unit
- modified API /webida/api/app/myapps to accept user info from request body
- modified API /webida/api/fs to acceps user info from request body
> [FEATURE] (#82) implemented guest-account-garbage-collection 

- src/server/auth/lib/user-manager.js
- src/server/batch/batch.js
- src/server/conf/default-conf.js
- added user.isGuest when user.email starts with guest prefix
- fixed guest password using password prefix and sequence number
- removed guestMode.enable in config
> added isGuest on GET myinfo

- doc/monitor/dbmon-create.sql
- src/server/app/app.js
- src/server/common/pfdb.js
- src/server/common/profiler.js
- src/server/conf/default-conf.js
- src/server/mon/lib/pf-manager.js
- src/server/mon/mon.js
- added monitoring server unit.
- added configurations of monitoring server to default-conf.js.
- added RESTful APIs for query of profiling.
- added client cookies for monitoring server url to app server.
> [FEATURE] added monitoring server

- src/server/auth/lib/user-manager.js
[DESC.] The webpage was just redirected to Webida site,
not logged in automatically after resetting password.
But the automatic login looks better UX and signup already works as this.
So modify to log in automatically after resetting password.
Change-Id: Ib15970c0e229fcf086d1037b470dadd8dc58ad8e
Signed-off-by: SangJin Kim <sangjin3.kim@samsung.com>
> [IMPROVEMENT] Modify to log in automatically after resetting password.

- src/server/auth/lib/user-manager.js
Related With webida/webida-client#253
> [BUGFIX] Resolve issues on Github login

- .gitmodules
- doc/advanced-guide.md
- src/server/app/lib/app-manager.js
- src/server/auth/lib/oauth2-manager.js
- src/server/auth/lib/user-manager.js
- src/server/conf/default-conf.js
- update-system-apps.sh
[DESC.]
- add `app-dashboard` repository as a git submodule
- download and deploy `app-dashboard` as a system app
- fix the way to make redirect url for system clients
- fix `update-system-apps.sh` and `app-manager.js` for any non npm modules (they have not `package.json` file)
- update document (advanced-guide)
> [TASK] Refactoring on system app/client installation

- src/server/auth/auth.js
- src/server/conf/default-conf.js
- src/system-configs/upstart-configs/units/webida-batch.conf
resolving #141 and misc. fixes
- added HOME env to webida-batch.conf
- removed some obsolute configurations in default-conf.js
- added some jshint suppression in auth.js
> fix batch upstart config

- src/server/common/auth-manager.js
> [BUGFIX] checkAuthorize - removed fsid argument in _buildAuthorizeRequest

- src/server/fs/lib/fs-manager.js
[DESC.]
- add handler for 'file.created' and 'file.updated' notifications from server
- and new topics, 'remote/persistence/created' and 'remote/persistence/updated', became to be used by client.
Related with https://github.com/kyungmi/webida-client/commit/58bd25e5331874ff6032c96a51a57ffcf18df3a1
> [IMPROVEMENT] Specify topics related with file

- src/server/auth/auth.js
- src/server/fs/fs.js
[DESC.]
- change filtering pattern in `fs.js` and `auth.js`
> [BUGFIX] #114 Some FS and Auth APIs are not collected by profiler

- src/server/auth/views/login.js
- src/server/fs/fs.js
- [FEATURE] #170 It is not necessary to clean email field when login is failed.
- [CODE_CONVENTION] fs.js
> [FEATURE] #170 It is not necessary to clean email field when login is failed.

- src/server/fs/lib/fs-manager.js
- If `mayNotExist` options is true, server will response with 204(No Conent) status code in error case of 404.
webida/webida-client#865
> [IMPROVEMENT] Too many 404 errors for tern  requests

- src/server/auth/auth.js
express(middleware) send error html to client.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/194)
> [TASK] Fix auth error handle logic in auth.js

- src/server/fs-backup.js
- src/server/fs-uninstall.js
- src/server/fs/lib/container/docker.js
- src/server/lxc-to-docker.js
- remove un-unsed code
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/199)
> [TASK] fix a jshint error

- src/install-script/install-server.sh
- src/server/all-install.sh
- src/server/app-install.js
- src/server/app/lib/app-manager.js
- src/server/package.json
- systeam app is registed in DB when system app installing
- systeam app's real files (source codes) are not installed
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/200)
> [TASK] Fix a system app install process

- src/server/common/conf-manager.js
- default-conf.js file support
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/201)
> [TASK] Fix to server configuration file support

- src/server/create-site-conf.js
- check domain value
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/203)
> [TASK] Fix a site configuration creation script logic

- src/server/auth/lib/user-manager.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/webida/webida-server/205)
> made mailer transport reusable
